// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: service
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.31.1
// Source:
//   - api/logs/logapi.proto

package svcgen

import (
	smw "ag-core/ag/ag_ext"
	logs "ag-layout-demo/api/logs"
	service "ag-layout-demo/internal/service"
	"context"
	slog "log/slog"
)

// LogServerProxy 服务代理
type LogServerProxy struct {
	impl     *service.LogServerImpl
	handlers map[string]smw.HandlerFunc
}

// NewLogServerProxy 创建LogServerProxy
func NewLogServerProxy(service *service.LogServerImpl, mws []smw.PrioritizedMiddleware) logs.LogServer {
	proxy := &LogServerProxy{
		impl:     service,
		handlers: make(map[string]smw.HandlerFunc),
	}

	// 注册处理链
	proxy.handlers["BatchLog"] = smw.RegisterHandler("BatchLog", mws, func(ctx context.Context, req interface{}) (interface{}, error) {
		return proxy.impl.BatchLog(ctx, req.(*logs.BatchLogRequest))
	})
	// FIXME StreamLog 流式接口暂不支持代理

	return proxy
}

// BatchLog LogServerProxy proxy
func (p *LogServerProxy) BatchLog(ctx context.Context, req *logs.BatchLogRequest) (*logs.BatchLogResponse, error) {
	methodName := "BatchLog"
	handler := p.handlers[methodName]

	res, err := handler(ctx, req)
	if err != nil {
		slog.Error("failed to handle request!", "method", methodName, "error", err)
		return nil, err
	}

	return res.(*logs.BatchLogResponse), nil
}

// StreamLog LogServerProxy proxy ClientStreaming
func (p *LogServerProxy) StreamLog(stream logs.LogServer_StreamLogServer) error {
	// FIXME 流式接口暂不支持代理，直接调用实现
	return p.impl.StreamLog(stream)
}
