// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - student/student.proto

package svcgen

import (
	ag_service "ag-core/ag/ag_service"
	student "ag-layout-demo/api/student"
	service "ag-layout-demo/internal/service"
	"context"
	"fmt"
	slog "log/slog"
)

// ServiceInfo interface level

var StudentServiceServiceInfo = ag_service.NewServiceInfo(
	"student",
	"StudentService",
	(*student.StudentService)(nil),
)

var StudentServiceCreateStudentCallInfo = ag_service.NewCallInfo(
	StudentServiceServiceInfo,
	"CreateStudent",
	false,
	false,
)

var StudentServiceGetStudentCallInfo = ag_service.NewCallInfo(
	StudentServiceServiceInfo,
	"GetStudent",
	false,
	false,
)

var StudentServiceCallInfos = map[string]*ag_service.CallInfo{
	"CreateStudent": StudentServiceCreateStudentCallInfo,
	"GetStudent":    StudentServiceGetStudentCallInfo,
}

// StudentServiceProxy 服务代理
type StudentServiceProxy struct {
	ag_service.AgServiceProxyBase
	impl *service.StudentServiceImpl
}

// NewStudentServiceProxy 创建StudentServiceProxy
func NewStudentServiceProxy(
	impl *service.StudentServiceImpl,
	agServiceBuilder ag_service.AgServiceBuilder,
	mws []ag_service.MiddlewareProvider,
) (student.StudentService, error) {

	p := &StudentServiceProxy{
		impl: impl,
		AgServiceProxyBase: ag_service.NewAgServiceProxyBase(
			StudentServiceServiceInfo,
			StudentServiceCallInfos,
		),
	}

	for _, cif := range p.CallInfos {
		if cif.IsClientStreaming() || cif.IsServerStreaming() {
			slog.Warn("agServiceProxy buildskip streaming method", "call_name", cif.CallName)
			continue
		}

		// 根据方法信息构建Endpoints
		oriEndpoint, err := p.getOriginalHandler(cif)
		if err != nil {
			return nil, err
		}
		endpoint, err := agServiceBuilder.BuildEndpointChain(
			cif,
			mws,
			oriEndpoint,
		)
		if err != nil {
			return nil, err
		}
		// 注册endpoint
		p.RegisterEndpoint(cif.CallName(), endpoint)
	}

	return p, nil
}

// CreateStudent StudentServiceProxy proxy
func (p *StudentServiceProxy) CreateStudent(ctx context.Context, req *student.CreateStudentRequest) (*student.Student, error) {
	endpoint := p.GetEndpoint("CreateStudent")

	resp, err := endpoint(ctx, req)
	if err != nil {
		slog.Error("failed to handle request!", "method", "CreateStudent", "error", err)
		return nil, err
	}

	return resp.(*student.Student), nil
}

// GetStudent StudentServiceProxy proxy
func (p *StudentServiceProxy) GetStudent(ctx context.Context, req *student.GetStudentRequest) (*student.Student, error) {
	endpoint := p.GetEndpoint("GetStudent")

	resp, err := endpoint(ctx, req)
	if err != nil {
		slog.Error("failed to handle request!", "method", "GetStudent", "error", err)
		return nil, err
	}

	return resp.(*student.Student), nil
}

// getOriginalHandler
func (p *StudentServiceProxy) getOriginalHandler(cif *ag_service.CallInfo) (ag_service.Endpoint, error) {
	switch cif.CallName() {
	case "CreateStudent":
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			return p.impl.CreateStudent(ctx, req.(*student.CreateStudentRequest))
		}, nil
	case "GetStudent":
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			return p.impl.GetStudent(ctx, req.(*student.GetStudentRequest))
		}, nil
	default:
		return nil, fmt.Errorf("handler for method %s not implemented", cif.CallName)
	}
}
