// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: package_group
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.31.1
// Source:
//   - api/logs/logapi.proto

package svcgen

import (
	smw "ag-core/ag/ag_ext"
	logs "ag-layout-demo/api/logs"
	service "ag-layout-demo/internal/service"
	fx "go.uber.org/fx"
)

var FxlogsServiceProxyModule = fx.Module("fx-logs-service-proxy",
	fx.Provide(
		NewLogServerProxyWithFxIn,
	),
)

// FxInLogServerMiddleware servcie middleware inject params
type FxInLogServerMiddleware struct {
	smw.BaseFxMiddlewareParams
	CustomMws []smw.PrioritizedMiddleware `group:"fx_logserver_service_middleware" ,optional:"true"`
}

// NewLogServerProxyWithFxIn create LogServer proxy with fx inject
func NewLogServerProxyWithFxIn(in FxInLogServerMiddleware, svc *service.LogServerImpl) logs.LogServer {
	return NewLogServerProxy(svc, append(in.GlobalMws, in.CustomMws...))
}

func init() {
	AddFxServiceWithProxyOpt(
		fx.Provide(
			service.NewLogServerImpl, // constructor return impl
			NewLogServerProxyWithFxIn,
		),
	)
}
