// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: package_group
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.31.1
// Source:
//   - api/hzw/hellostreaming.proto
//   - api/hzw/hzw2.proto
//   - api/hzw/hzw.proto

package svcgen

import (
	smw "ag-core/ag/ag_ext"
	hzw "ag-layout-demo/api/hzw"
	service "ag-layout-demo/internal/service"
	fx "go.uber.org/fx"
)

var FxhzwServiceProxyModule = fx.Module("fx-hzw-service-proxy",
	fx.Provide(
		NewHelloStreamProxyWithFxIn,
		NewHzwHello2ProxyWithFxIn,
		NewHzwHelloProxyWithFxIn,
	),
)

// FxInHelloStreamMiddleware servcie middleware inject params
type FxInHelloStreamMiddleware struct {
	smw.BaseFxMiddlewareParams
	CustomMws []smw.PrioritizedMiddleware `group:"fx_hellostream_service_middleware" ,optional:"true"`
}

// NewHelloStreamProxyWithFxIn create HelloStream proxy with fx inject
func NewHelloStreamProxyWithFxIn(in FxInHelloStreamMiddleware, svc *service.HelloStreamImpl) hzw.HelloStream {
	return NewHelloStreamProxy(svc, append(in.GlobalMws, in.CustomMws...))
}

// FxInHzwHello2Middleware servcie middleware inject params
type FxInHzwHello2Middleware struct {
	smw.BaseFxMiddlewareParams
	CustomMws []smw.PrioritizedMiddleware `group:"fx_hzwhello2_service_middleware" ,optional:"true"`
}

// NewHzwHello2ProxyWithFxIn create HzwHello2 proxy with fx inject
func NewHzwHello2ProxyWithFxIn(in FxInHzwHello2Middleware, svc *service.HzwHello2Impl) hzw.HzwHello2 {
	return NewHzwHello2Proxy(svc, append(in.GlobalMws, in.CustomMws...))
}

// FxInHzwHelloMiddleware servcie middleware inject params
type FxInHzwHelloMiddleware struct {
	smw.BaseFxMiddlewareParams
	CustomMws []smw.PrioritizedMiddleware `group:"fx_hzwhello_service_middleware" ,optional:"true"`
}

// NewHzwHelloProxyWithFxIn create HzwHello proxy with fx inject
func NewHzwHelloProxyWithFxIn(in FxInHzwHelloMiddleware, svc *service.HzwHelloImpl) hzw.HzwHello {
	return NewHzwHelloProxy(svc, append(in.GlobalMws, in.CustomMws...))
}

func init() {
	AddFxServiceWithProxyOpt(
		fx.Provide(
			service.NewHelloStreamImpl, // constructor return impl
			NewHelloStreamProxyWithFxIn,
			service.NewHzwHello2Impl, // constructor return impl
			NewHzwHello2ProxyWithFxIn,
			service.NewHzwHelloImpl, // constructor return impl
			NewHzwHelloProxyWithFxIn,
		),
	)
}
