// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - student/student.proto

package svcgen

import (
	ag_service "ag-core/ag/ag_service"
	student "ag-layout-demo/api/student"
	service "ag-layout-demo/internal/service"
	fx "go.uber.org/fx"
)

// FxInStudentServiceMiddleware servcie middleware inject params
type FxInStudentServiceMiddleware struct {
	fx.In

	AgServiceBuilder ag_service.AgServiceBuilder

	CustomMws []ag_service.MiddlewareProvider `group:"fx_studentservice_service_middleware" ,optional:"true"`
}

// NewStudentServiceProxyWithFxIn create StudentService proxy with fx inject
func NewStudentServiceProxyWithFxIn(in FxInStudentServiceMiddleware, svc *service.StudentServiceImpl) (student.StudentService, error) {
	return NewStudentServiceProxy(svc, in.AgServiceBuilder, in.CustomMws)
}

func init() {
	AddFxServiceWithProxyOpt(
		fx.Provide(
			service.NewStudentServiceImpl, // constructor return impl
			NewStudentServiceProxyWithFxIn,
		),
	)
}
