// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: package_group
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.31.1
// Source:
//   - api/logs/logapi.proto

package svcgen

import (
	service "ag-layout-demo/internal/service"
	fx "go.uber.org/fx"
)

func init() {
	AddFxServiceOpt(
		fx.Provide(
			service.NewLogServerImplI, // constructor return interface
		),
	)
}
