// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
// Code generated by agservice. DO NOT EDIT!!!
//
// GenScope: module
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - agservice: v0.0.1
//   - protoc: v6.31.1
// Source:
//   - api/logs/logapi.proto
//   - api/hzw/hellostreaming.proto
//   - api/hzw/hzw2.proto
//   - api/hzw/hzw.proto

package svcgen

import (
	fx "go.uber.org/fx"
	"sync"
)

var (
	_lock1                 sync.Mutex
	fxServiceOpts          []fx.Option
	_lock2                 sync.Mutex
	fxServiceWithProxyOpts []fx.Option
)

// FxServiceModule return service fx module
func FxServiceModule() fx.Option {
	_lock1.Lock()
	defer _lock1.Unlock()
	return fx.Module("fx-service", fxServiceOpts...)
}

// FxServiceWithProxyModule return service fx module with service proxy
func FxServiceWithProxyModule() fx.Option {
	_lock2.Lock()
	defer _lock2.Unlock()
	return fx.Module("fx-service-with-proxy", fxServiceWithProxyOpts...)
}

// AddFxServiceOpt add fx service option.
func AddFxServiceOpt(opt fx.Option) {
	_lock1.Lock()
	defer _lock1.Unlock()
	if fxServiceOpts == nil {
		fxServiceOpts = []fx.Option{}
	}
	fxServiceOpts = append(fxServiceOpts, opt)
}

// AddFxServiceWithProxyOpt add fx service option with proxy.
func AddFxServiceWithProxyOpt(opt fx.Option) {
	_lock2.Lock()
	defer _lock2.Unlock()
	if fxServiceWithProxyOpts == nil {
		fxServiceWithProxyOpts = []fx.Option{}
	}
	fxServiceWithProxyOpts = append(fxServiceWithProxyOpts, opt)
}
