// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - aghertz: v0.0.1
//   - hertz: v0.10.0
//   - protoc: v6.31.1
// Source:
//   - api/hzw/hzw.proto

package adpinit

import (
	hzwhello "ag-layout-demo/api/hzw/hzwhello"
)

func init() {
	AddFxAdapterOpt(hzwhello.FxHzwHelloHertzModule)
}
