// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
//
// GenScope: module
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - agserver: v0.0.1
//   - protoc: v6.31.1
// Source:
//   - api/hzw/hellostreaming.proto
//   - api/hzw/hzw2.proto
//   - api/hzw/hzw.proto
//   - api/logs/logapi.proto

package adpinit

import (
	fx "go.uber.org/fx"
	"sync"
)

var (
	fxAdapterLock sync.Mutex
	fxAdapterOpts []fx.Option
)

// AddFxAdapterOpt add fx adapter option.
func AddFxAdapterOpt(opt fx.Option) {
	fxAdapterLock.Lock()
	defer fxAdapterLock.Unlock()
	if fxAdapterOpts == nil {
		fxAdapterOpts = []fx.Option{}
	}
	fxAdapterOpts = append(fxAdapterOpts, opt)
}

// GetFxAdapterOpt .
func GetFxAdapterOpt() []fx.Option {
	fxAdapterLock.Lock()
	defer fxAdapterLock.Unlock()
	return fxAdapterOpts
}
