// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - aghertz: v0.0.1
//   - hertz: v0.10.0
//   - protoc: v6.31.1
// Source:
//   - api/logs/logapi.proto

package adpinit

import (
	logserver "ag-layout-demo/api/logs/logserver"
)

func init() {
	AddFxAdapterOpt(logserver.FxLogServerHertzModule)
}
