// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - agkitex: v0.0.1
//   - kitex: v0.14.1
//   - protoc: v6.31.1
// Source:
//   - api/hzw/hellostreaming.proto

package adpinit

import (
	hellostream "ag-layout-demo/api/hzw/hellostream"
)

func init() {
	AddFxAdapterOpt(hellostream.FxHelloStreamKitexModule)
}
