// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - agkitex: v0.0.1
//   - kitex: v0.14.1
//   - protoc: v6.31.1
// Source:
//   - api/hzw/hellostreaming.proto

package hellostream

import (
	fx "go.uber.org/fx"
)

// FxHelloStreamKitexModule fx module
var FxHelloStreamKitexModule = fx.Module("fx_HelloStream_kitex",
	FxHelloStreamKitexRegProvider,
)

// FxHelloStreamKitexRegProvider fx provide
var FxHelloStreamKitexRegProvider = fx.Provide(
	fx.Annotate(
		Register_HelloStream_KitexServer,
		fx.ResultTags(`group:"ag_kitex_server_registrars"`),
	),
)
