// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - aghertz: v0.0.1
//   - hertz: v0.10.0
//   - protoc: v6.31.1
// Source:
//   - api/logs/logapi.proto

package logserver

import (
	server "ag-core/ag/ag_hertz/server"
	logs "ag-layout-demo/api/logs"
	"context"
	app "github.com/cloudwego/hertz/pkg/app"
	consts "github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Register_LogServer_BatchLog_0_POST_Hertz
// @Name: BatchLog
// @Method: POST
// @Path: /v1/logs/batch
func Register_LogServer_BatchLog_0_POST_Hertz(s logs.LogServer) server.Option {
	return server.WithRoute(&server.Route{
		HttpMethod:   "POST",
		RelativePath: "/v1/logs/batch",
		Handlers:     append(make([]app.HandlerFunc, 0), _LogServer_BatchLog_0_HTTP_Handler(s)),
	})
}

func _LogServer_BatchLog_0_HTTP_Handler(s logs.LogServer) func(ctx context.Context, c *app.RequestContext) {
	return func(ctx context.Context, c *app.RequestContext) {
		//var in = new(logs.BatchLogRequest)
		var in logs.BatchLogRequest
		// BindByContentType 当Method为GET时，会自动调用BindQuery，其他方法会调用对应Bind
		if err := c.BindByContentType(&in); err != nil {
			c.String(consts.StatusBadRequest, err.Error())
			return
		}

		resp, err := s.BatchLog(ctx, &in)
		if err != nil {
			// TODO 增强异常处理
			c.String(consts.StatusInternalServerError, err.Error())
			return
		}

		// c.JSON 会自动将 Content-Type 设置为 application/json,
		c.JSON(consts.StatusOK, resp)
	}
}

// FIXME LogServer.StreamLog is streaming method
