// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - aghertz: v0.0.1
//   - hertz: v0.10.0
//   - protoc: v6.31.1
// Source:
//   - api/logs/logapi.proto

package logserver

import (
	fx "go.uber.org/fx"
)

var FxLogServerHertzModule = fx.Module("fx_LogServer_hertz",
	FxLogServer_BatchLog_hertz_RegProvider,
)
var FxLogServer_BatchLog_hertz_RegProvider = fx.Provide(
	fx.Annotate(
		Register_LogServer_BatchLog_0_POST_Hertz,
		fx.ResultTags(`group:"hertz_router_options"`),
	),
)
