// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - agkitex: v0.0.1
//   - kitex: v0.14.1
//   - protoc: v6.31.1
// Source:
//   - api/logs/logapi.proto

package logserver

import (
	fx "go.uber.org/fx"
)

// FxLogServerKitexModule fx module
var FxLogServerKitexModule = fx.Module("fx_LogServer_kitex",
	FxLogServerKitexRegProvider,
)

// FxLogServerKitexRegProvider fx provide
var FxLogServerKitexRegProvider = fx.Provide(
	fx.Annotate(
		Register_LogServer_KitexServer,
		fx.ResultTags(`group:"ag_kitex_server_registrars"`),
	),
)
