// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - student/student.proto

package studentservice

import (
	hserver "ag-core/contribute/aghertz/server"
	student "ag-layout-demo/api/student"
	"context"
	app "github.com/cloudwego/hertz/pkg/app"
	consts "github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Router_StudentService_CreateStudent_0_POST_Hertz
// @Name: CreateStudent
// @Method: POST
// @Path: student/create
func Router_StudentService_CreateStudent_0_POST_Hertz(s student.StudentService) *hserver.Route {
	return &hserver.Route{
		HttpMethod:   "POST",
		RelativePath: "student/create",
		Handlers:     append(make([]app.HandlerFunc, 0), _StudentService_CreateStudent_0_HTTP_Handler(s)),
	}
}

func _StudentService_CreateStudent_0_HTTP_Handler(s student.StudentService) func(ctx context.Context, c *app.RequestContext) {
	return func(ctx context.Context, c *app.RequestContext) {
		//var in = new(student.CreateStudentRequest)
		var in student.CreateStudentRequest
		// BindByContentType 当Method为GET时，会自动调用BindQuery，其他方法会调用对应Bind
		if err := c.BindByContentType(&in); err != nil {
			c.String(consts.StatusBadRequest, err.Error())
			return
		}

		resp, err := s.CreateStudent(ctx, &in)
		if err != nil {
			// TODO 增强异常处理
			c.String(consts.StatusInternalServerError, err.Error())
			return
		}

		// c.JSON 会自动将 Content-Type 设置为 application/json,
		c.JSON(consts.StatusOK, resp)
	}
}

// Router_StudentService_GetStudent_0_GET_Hertz
// @Name: GetStudent
// @Method: GET
// @Path: student/get/:Stuno
func Router_StudentService_GetStudent_0_GET_Hertz(s student.StudentService) *hserver.Route {
	return &hserver.Route{
		HttpMethod:   "GET",
		RelativePath: "student/get/:Stuno",
		Handlers:     append(make([]app.HandlerFunc, 0), _StudentService_GetStudent_0_HTTP_Handler(s)),
	}
}

func _StudentService_GetStudent_0_HTTP_Handler(s student.StudentService) func(ctx context.Context, c *app.RequestContext) {
	return func(ctx context.Context, c *app.RequestContext) {
		//var in = new(student.GetStudentRequest)
		var in student.GetStudentRequest
		// 无Body定义的方法，BindQuery，否则使用BindByContentType
		if err := c.BindQuery(&in); err != nil {
			c.String(consts.StatusBadRequest, err.Error())
			return
		}
		if err := c.BindPath(&in); err != nil {
			c.String(consts.StatusBadRequest, err.Error())
			return
		}

		resp, err := s.GetStudent(ctx, &in)
		if err != nil {
			// TODO 增强异常处理
			c.String(consts.StatusInternalServerError, err.Error())
			return
		}

		// c.JSON 会自动将 Content-Type 设置为 application/json,
		c.JSON(consts.StatusOK, resp)
	}
}

// Router_StudentService_GetStudent_1_GET_Hertz
// @Name: GetStudent
// @Method: GET
// @Path: student/get
func Router_StudentService_GetStudent_1_GET_Hertz(s student.StudentService) *hserver.Route {
	return &hserver.Route{
		HttpMethod:   "GET",
		RelativePath: "student/get",
		Handlers:     append(make([]app.HandlerFunc, 0), _StudentService_GetStudent_1_HTTP_Handler(s)),
	}
}

func _StudentService_GetStudent_1_HTTP_Handler(s student.StudentService) func(ctx context.Context, c *app.RequestContext) {
	return func(ctx context.Context, c *app.RequestContext) {
		//var in = new(student.GetStudentRequest)
		var in student.GetStudentRequest
		// 无Body定义的方法，BindQuery，否则使用BindByContentType
		if err := c.BindQuery(&in); err != nil {
			c.String(consts.StatusBadRequest, err.Error())
			return
		}

		resp, err := s.GetStudent(ctx, &in)
		if err != nil {
			// TODO 增强异常处理
			c.String(consts.StatusInternalServerError, err.Error())
			return
		}

		// c.JSON 会自动将 Content-Type 设置为 application/json,
		c.JSON(consts.StatusOK, resp)
	}
}
