// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - student/student.proto

package studentservice

import (
	agclient "ag-core/contribute/aghertz/aghertzclient"
	student "ag-layout-demo/api/student"
	"context"
	"github.com/cloudwego/hertz/pkg/app/client"
	config "github.com/cloudwego/hertz/pkg/common/config"
)

// StudentServiceHertzClient is the hertz client for StudentService.
type StudentServiceHertzClient interface {
	// CreateStudent
	CreateStudent(ctx context.Context, req *student.CreateStudentRequest, opts ...config.RequestOption) (resp *student.Student, err error)
	// GetStudent
	GetStudent(ctx context.Context, req *student.GetStudentRequest, opts ...config.RequestOption) (resp *student.Student, err error)
}

// NewStudentServiceHertzClient is the constructor for StudentServiceHertzClient.
func NewStudentServiceHertzClient(hc *client.Client, opts ...agclient.AgHertzClientOption) StudentServiceHertzClient {
	client := &StudentServiceHertzClientImpl{
		HertzBaseClient: agclient.NewHertzBaseClient(hc, opts...),
	}
	return client
}

// StudentServiceHertzClientImpl is the hertz client impl for StudentService.
type StudentServiceHertzClientImpl struct {
	*agclient.HertzBaseClient
}

// CreateStudent client impl CreateStudent
func (c *StudentServiceHertzClientImpl) CreateStudent(ctx context.Context, req *student.CreateStudentRequest, opts ...config.RequestOption) (*student.Student, error) {
	var resp student.Student

	// 构建请求配置
	reqParam := &agclient.RequestParam{
		Method: "POST",
		Path:   "student/create",
	}
	rerr := c.DoRequest(ctx, reqParam, req, &resp, opts...)
	if rerr != nil {
		return nil, rerr
	}

	return &resp, nil
}

// GetStudent client impl GetStudent
func (c *StudentServiceHertzClientImpl) GetStudent(ctx context.Context, req *student.GetStudentRequest, opts ...config.RequestOption) (*student.Student, error) {
	var resp student.Student

	// 构建请求配置
	reqParam := &agclient.RequestParam{
		Method: "GET",
		Path:   "student/get/:Stuno",
		PathVars: map[string]string{
			"Stuno": req.GetStuno(),
		},
	}
	rerr := c.DoRequest(ctx, reqParam, nil, &resp, opts...)
	if rerr != nil {
		return nil, rerr
	}

	return &resp, nil
}
