// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - student/student.proto

package studentservice

import (
	hserver "ag-core/contribute/aghertz/server"
	fx "go.uber.org/fx"
)

var FxStudentServiceHertzModule = fx.Module("fx_StudentService_hertz",
	FxStudentService_CreateStudent_hertz_RegProvider,
	FxStudentService_GetStudent_hertz_RegProvider,
)
var FxStudentService_CreateStudent_hertz_RegProvider = fx.Provide(
	hserver.NewFxServerRouteProvider(
		Router_StudentService_CreateStudent_0_POST_Hertz,
	),
)
var FxStudentService_GetStudent_hertz_RegProvider = fx.Provide(
	hserver.NewFxServerRouteProvider(
		Router_StudentService_GetStudent_0_GET_Hertz,
	),

	hserver.NewFxServerRouteProvider(
		Router_StudentService_GetStudent_1_GET_Hertz,
	),
)
