// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - student/student.proto

package studentservice

import (
	akserver "ag-core/contribute/agkitex/server"
	fx "go.uber.org/fx"
)

// FxStudentServiceKitexModule fx module
var FxStudentServiceKitexModule = fx.Module("fx_StudentService_kitex",
	FxStudentServiceKitexRegProvider,
)

// FxStudentServiceKitexRegProvider fx provide
var FxStudentServiceKitexRegProvider = fx.Provide(

	akserver.NewFxAgKitexServiceRegistry(
		Register_StudentService_KitexServer,
	),
)
