// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - student/student.proto

package studentservice

import (
	student "ag-layout-demo/api/student"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var studentServiceServiceMethods = map[string]kitex.MethodInfo{
	"createStudent": kitex.NewMethodInfo(
		createStudentHandler,
		newCreateStudentArgs,
		newCreateStudentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"getStudent": kitex.NewMethodInfo(
		getStudentHandler,
		newGetStudentArgs,
		newGetStudentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	studentServiceServiceInfo                = NewServiceInfo()
	studentServiceServiceInfoForClient       = NewServiceInfoForClient()
	studentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return studentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return studentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return studentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "studentService"
	handlerType := (*student.StudentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range studentServiceServiceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "student",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.14.1_by_aggen", // FIXME 模板生成时应该获取kitex版本
		Extra:           extra,
	}
	return svcInfo
}

func createStudentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(student.CreateStudentRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(student.StudentService).CreateStudent(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateStudentArgs:
		success, err := handler.(student.StudentService).CreateStudent(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateStudentResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateStudentArgs() interface{} {
	return &CreateStudentArgs{}
}

func newCreateStudentResult() interface{} {
	return &CreateStudentResult{}
}

type CreateStudentArgs struct {
	Req *student.CreateStudentRequest
}

func (p *CreateStudentArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateStudentArgs) Unmarshal(in []byte) error {
	msg := new(student.CreateStudentRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateStudentArgs_Req_DEFAULT *student.CreateStudentRequest

func (p *CreateStudentArgs) GetReq() *student.CreateStudentRequest {
	if !p.IsSetReq() {
		return CreateStudentArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateStudentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateStudentArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateStudentResult struct {
	Success *student.Student
}

var CreateStudentResult_Success_DEFAULT *student.Student

func (p *CreateStudentResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateStudentResult) Unmarshal(in []byte) error {
	msg := new(student.Student)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateStudentResult) GetSuccess() *student.Student {
	if !p.IsSetSuccess() {
		return CreateStudentResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateStudentResult) SetSuccess(x interface{}) {
	p.Success = x.(*student.Student)
}

func (p *CreateStudentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateStudentResult) GetResult() interface{} {
	return p.Success
}

func getStudentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(student.GetStudentRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(student.StudentService).GetStudent(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetStudentArgs:
		success, err := handler.(student.StudentService).GetStudent(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetStudentResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetStudentArgs() interface{} {
	return &GetStudentArgs{}
}

func newGetStudentResult() interface{} {
	return &GetStudentResult{}
}

type GetStudentArgs struct {
	Req *student.GetStudentRequest
}

func (p *GetStudentArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetStudentArgs) Unmarshal(in []byte) error {
	msg := new(student.GetStudentRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetStudentArgs_Req_DEFAULT *student.GetStudentRequest

func (p *GetStudentArgs) GetReq() *student.GetStudentRequest {
	if !p.IsSetReq() {
		return GetStudentArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetStudentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetStudentArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetStudentResult struct {
	Success *student.Student
}

var GetStudentResult_Success_DEFAULT *student.Student

func (p *GetStudentResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetStudentResult) Unmarshal(in []byte) error {
	msg := new(student.Student)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetStudentResult) GetSuccess() *student.Student {
	if !p.IsSetSuccess() {
		return GetStudentResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetStudentResult) SetSuccess(x interface{}) {
	p.Success = x.(*student.Student)
}

func (p *GetStudentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetStudentResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateStudent(ctx context.Context, Req *student.CreateStudentRequest) (r *student.Student, err error) {
	var _args CreateStudentArgs
	_args.Req = Req
	var _result CreateStudentResult
	if err = p.c.Call(ctx, "createStudent", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetStudent(ctx context.Context, Req *student.GetStudentRequest) (r *student.Student, err error) {
	var _args GetStudentArgs
	_args.Req = Req
	var _result GetStudentResult
	if err = p.c.Call(ctx, "getStudent", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
