// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - agkitex: v0.0.1
//   - kitex: v0.14.1
//   - protoc: v6.31.1
// Source:
//   - api/hzw/hzw.proto

package hzwhello

import (
	akserver "ag-core/ag/ag_kitex/server"
	hzw "ag-layout-demo/api/hzw"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler hzw.HzwHello, opts ...server.Option) server.Server {
	var options []server.Option
	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler hzw.HzwHello, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}

// Register_HzwHello_KitexServer ag_kitex service register.
func Register_HzwHello_KitexServer(srv hzw.HzwHello) akserver.Option {
	return akserver.WithServiceRegistrar(&akserver.ServiceRegistrar{
		ServiceInfo: NewServiceInfo(),
		Handler:     srv,
	})
}
