// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - agkitex: v0.0.1
//   - kitex: v0.14.1
//   - protoc: v6.31.1
// Source:
//   - api/hzw/hzw.proto

package hzwhello

import (
	hzw "ag-layout-demo/api/hzw"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	streamcall "github.com/cloudwego/kitex/client/callopt/streamcall"
	streamclient "github.com/cloudwego/kitex/client/streamclient"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	transport "github.com/cloudwego/kitex/transport"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	HelloHzw(ctx context.Context, Req *hzw.HzwRequest, callOptions ...callopt.Option) (r *hzw.HzwReply, err error)
	HelloHzwStream(ctx context.Context, callOptions ...callopt.Option) (stream HzwHello_HelloHzwStreamClient, err error)
}

// StreamClient is designed to provide Interface for Streaming APIs.
type StreamClient interface {
	HelloHzwStream(ctx context.Context, callOptions ...streamcall.Option) (stream HzwHello_HelloHzwStreamClient, err error)
}

type HzwHello_HelloHzwStreamClient interface {
	streaming.Stream
	Send(*hzw.HzwRequest) error
	Recv() (*hzw.HzwReply, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kHzwHelloClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kHzwHelloClient struct {
	*kClient
}

func (p *kHzwHelloClient) HelloHzw(ctx context.Context, Req *hzw.HzwRequest, callOptions ...callopt.Option) (r *hzw.HzwReply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.HelloHzw(ctx, Req)
}

func (p *kHzwHelloClient) HelloHzwStream(ctx context.Context, callOptions ...callopt.Option) (stream HzwHello_HelloHzwStreamClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.HelloHzwStream(ctx)
}

// NewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
func NewStreamClient(destService string, opts ...streamclient.Option) (StreamClient, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))
	options = append(options, client.WithTransportProtocol(transport.GRPC))
	options = append(options, streamclient.GetClientOptions(opts)...)

	kc, err := client.NewClient(serviceInfoForStreamClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kHzwHelloStreamClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
// It panics if any error occurs.
func MustNewStreamClient(destService string, opts ...streamclient.Option) StreamClient {
	kc, err := NewStreamClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kHzwHelloStreamClient struct {
	*kClient
}

func (p *kHzwHelloStreamClient) HelloHzwStream(ctx context.Context, callOptions ...streamcall.Option) (stream HzwHello_HelloHzwStreamClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.HelloHzwStream(ctx)
}
