// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - agkitex: v0.0.1
//   - kitex: v0.14.1
//   - protoc: v6.31.1
// Source:
//   - api/hzw/hzw.proto

package hzwhello

import (
	fx "go.uber.org/fx"
)

// FxHzwHelloKitexModule fx module
var FxHzwHelloKitexModule = fx.Module("fx_HzwHello_kitex",
	FxHzwHelloKitexRegProvider,
)

// FxHzwHelloKitexRegProvider fx provide
var FxHzwHelloKitexRegProvider = fx.Provide(
	fx.Annotate(
		Register_HzwHello_KitexServer,
		fx.ResultTags(`group:"ag_kitex_server_registrars"`),
	),
)
