// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - aghertz: v0.0.1
//   - hertz: v0.10.0
//   - protoc: v6.31.1
// Source:
//   - api/hzw/hzw2.proto

package hzwhello2

import (
	fx "go.uber.org/fx"
)

var FxHzwHello2HertzModule = fx.Module("fx_HzwHello2_hertz",
	FxHzwHello2_HelloHzw2_hertz_RegProvider,
)
var FxHzwHello2_HelloHzw2_hertz_RegProvider = fx.Provide(
	fx.Annotate(
		Register_HzwHello2_HelloHzw2_0_GET_Hertz,
		fx.ResultTags(`group:"hertz_router_options"`),
	),
	fx.Annotate(
		Register_HzwHello2_HelloHzw2_1_GET_Hertz,
		fx.ResultTags(`group:"hertz_router_options"`),
	),
	fx.Annotate(
		Register_HzwHello2_HelloHzw2_2_GET_Hertz,
		fx.ResultTags(`group:"hertz_router_options"`),
	),
	fx.Annotate(
		Register_HzwHello2_HelloHzw2_3_POST_Hertz,
		fx.ResultTags(`group:"hertz_router_options"`),
	),
)
