// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - agkitex: v0.0.1
//   - kitex: v0.14.1
//   - protoc: v6.31.1
// Source:
//   - api/hzw/hzw2.proto

package hzwhello2

import (
	fx "go.uber.org/fx"
)

// FxHzwHello2KitexModule fx module
var FxHzwHello2KitexModule = fx.Module("fx_HzwHello2_kitex",
	FxHzwHello2KitexRegProvider,
)

// FxHzwHello2KitexRegProvider fx provide
var FxHzwHello2KitexRegProvider = fx.Provide(
	fx.Annotate(
		Register_HzwHello2_KitexServer,
		fx.ResultTags(`group:"ag_kitex_server_registrars"`),
	),
)
