// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - agkitex: v0.0.1
//   - kitex: v0.14.1
//   - protoc: v6.31.1
// Source:
//   - api/hzw/hzw2.proto

package hzwhello2

import (
	hzw "ag-layout-demo/api/hzw"
	"context"
	"errors"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var hzwHello2ServiceMethods = map[string]kitex.MethodInfo{
	"HelloHzw2": kitex.NewMethodInfo(
		helloHzw2Handler,
		newHelloHzw2Args,
		newHelloHzw2Result,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"HelloHzwStream2": kitex.NewMethodInfo(
		helloHzwStream2Handler,
		newHelloHzwStream2Args,
		newHelloHzwStream2Result,
		false,
		kitex.WithStreamingMode(kitex.StreamingBidirectional),
	),
}

var (
	hzwHello2ServiceInfo                = NewServiceInfo()
	hzwHello2ServiceInfoForClient       = NewServiceInfoForClient()
	hzwHello2ServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return hzwHello2ServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return hzwHello2ServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return hzwHello2ServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(true, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "HzwHello2"
	handlerType := (*hzw.HzwHello2)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range hzwHello2ServiceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api.hzw",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.14.1_by_aggen", // FIXME 模板生成时应该获取kitex版本
		Extra:           extra,
	}
	return svcInfo
}

func helloHzw2Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(hzw.HzwRequest2)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(hzw.HzwHello2).HelloHzw2(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *HelloHzw2Args:
		success, err := handler.(hzw.HzwHello2).HelloHzw2(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*HelloHzw2Result)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newHelloHzw2Args() interface{} {
	return &HelloHzw2Args{}
}

func newHelloHzw2Result() interface{} {
	return &HelloHzw2Result{}
}

type HelloHzw2Args struct {
	Req *hzw.HzwRequest2
}

func (p *HelloHzw2Args) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *HelloHzw2Args) Unmarshal(in []byte) error {
	msg := new(hzw.HzwRequest2)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var HelloHzw2Args_Req_DEFAULT *hzw.HzwRequest2

func (p *HelloHzw2Args) GetReq() *hzw.HzwRequest2 {
	if !p.IsSetReq() {
		return HelloHzw2Args_Req_DEFAULT
	}
	return p.Req
}

func (p *HelloHzw2Args) IsSetReq() bool {
	return p.Req != nil
}

func (p *HelloHzw2Args) GetFirstArgument() interface{} {
	return p.Req
}

type HelloHzw2Result struct {
	Success *hzw.HzwReply2
}

var HelloHzw2Result_Success_DEFAULT *hzw.HzwReply2

func (p *HelloHzw2Result) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *HelloHzw2Result) Unmarshal(in []byte) error {
	msg := new(hzw.HzwReply2)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *HelloHzw2Result) GetSuccess() *hzw.HzwReply2 {
	if !p.IsSetSuccess() {
		return HelloHzw2Result_Success_DEFAULT
	}
	return p.Success
}

func (p *HelloHzw2Result) SetSuccess(x interface{}) {
	p.Success = x.(*hzw.HzwReply2)
}

func (p *HelloHzw2Result) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *HelloHzw2Result) GetResult() interface{} {
	return p.Success
}

func helloHzwStream2Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	streamingArgs, ok := arg.(*streaming.Args)
	if !ok {
		return errInvalidMessageType
	}
	st := streamingArgs.Stream
	stream := &hzwHello2HelloHzwStream2Server{st}
	return handler.(hzw.HzwHello2).HelloHzwStream2(stream)
}

type hzwHello2HelloHzwStream2Client struct {
	streaming.Stream
}

func (x *hzwHello2HelloHzwStream2Client) DoFinish(err error) {
	if finisher, ok := x.Stream.(streaming.WithDoFinish); ok {
		finisher.DoFinish(err)
	} else {
		panic(fmt.Sprintf("streaming.WithDoFinish is not implemented by %T", x.Stream))
	}
}
func (x *hzwHello2HelloHzwStream2Client) Send(m *hzw.HzwRequest2) error {
	return x.Stream.SendMsg(m)
}
func (x *hzwHello2HelloHzwStream2Client) Recv() (*hzw.HzwReply2, error) {
	m := new(hzw.HzwReply2)
	return m, x.Stream.RecvMsg(m)
}

type hzwHello2HelloHzwStream2Server struct {
	streaming.Stream
}

func (x *hzwHello2HelloHzwStream2Server) Send(m *hzw.HzwReply2) error {
	return x.Stream.SendMsg(m)
}

func (x *hzwHello2HelloHzwStream2Server) Recv() (*hzw.HzwRequest2, error) {
	m := new(hzw.HzwRequest2)
	return m, x.Stream.RecvMsg(m)
}

func newHelloHzwStream2Args() interface{} {
	return &HelloHzwStream2Args{}
}

func newHelloHzwStream2Result() interface{} {
	return &HelloHzwStream2Result{}
}

type HelloHzwStream2Args struct {
	Req *hzw.HzwRequest2
}

func (p *HelloHzwStream2Args) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *HelloHzwStream2Args) Unmarshal(in []byte) error {
	msg := new(hzw.HzwRequest2)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var HelloHzwStream2Args_Req_DEFAULT *hzw.HzwRequest2

func (p *HelloHzwStream2Args) GetReq() *hzw.HzwRequest2 {
	if !p.IsSetReq() {
		return HelloHzwStream2Args_Req_DEFAULT
	}
	return p.Req
}

func (p *HelloHzwStream2Args) IsSetReq() bool {
	return p.Req != nil
}

func (p *HelloHzwStream2Args) GetFirstArgument() interface{} {
	return p.Req
}

type HelloHzwStream2Result struct {
	Success *hzw.HzwReply2
}

var HelloHzwStream2Result_Success_DEFAULT *hzw.HzwReply2

func (p *HelloHzwStream2Result) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *HelloHzwStream2Result) Unmarshal(in []byte) error {
	msg := new(hzw.HzwReply2)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *HelloHzwStream2Result) GetSuccess() *hzw.HzwReply2 {
	if !p.IsSetSuccess() {
		return HelloHzwStream2Result_Success_DEFAULT
	}
	return p.Success
}

func (p *HelloHzwStream2Result) SetSuccess(x interface{}) {
	p.Success = x.(*hzw.HzwReply2)
}

func (p *HelloHzwStream2Result) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *HelloHzwStream2Result) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) HelloHzw2(ctx context.Context, Req *hzw.HzwRequest2) (r *hzw.HzwReply2, err error) {
	var _args HelloHzw2Args
	_args.Req = Req
	var _result HelloHzw2Result
	if err = p.c.Call(ctx, "HelloHzw2", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) HelloHzwStream2(ctx context.Context) (HzwHello2_HelloHzwStream2Client, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "HelloHzwStream2", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &hzwHello2HelloHzwStream2Client{res.Stream}
	return stream, nil
}
