// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
// Code generated by aghertz. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - aghertz: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - student/student.proto

package adpinit

import (
	studentservice "ag-layout-demo/internal/adpgen/hertz/studentservice"
)

func init() {
	AddFxAdapterOpt(studentservice.FxStudentServiceHertzModule)
}
