// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
// Code generated by agkitex. DO NOT EDIT!!!
//
// GenScope: service
// Versions:
//   - agkitex: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - student/student.proto

package adpinit

import (
	studentservice "ag-layout-demo/internal/adpgen/kitex/studentservice"
)

func init() {
	AddFxAdapterOpt(studentservice.FxStudentServiceKitexModule)
}
