// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agserver: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - student/student.proto

package student

import (
	"context"
)

// StudentService defines the server interface for the StudentService service.
type StudentService interface {
	CreateStudent(context.Context, *CreateStudentRequest) (*Student, error)
	GetStudent(context.Context, *GetStudentRequest) (*Student, error)
}
