// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: student/student.proto

package student

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stuno         string                 `protobuf:"bytes,1,opt,name=stuno,proto3" json:"stuno,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentRequest) Reset() {
	*x = CreateStudentRequest{}
	mi := &file_student_student_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentRequest) ProtoMessage() {}

func (x *CreateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_student_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentRequest.ProtoReflect.Descriptor instead.
func (*CreateStudentRequest) Descriptor() ([]byte, []int) {
	return file_student_student_proto_rawDescGZIP(), []int{0}
}

func (x *CreateStudentRequest) GetStuno() string {
	if x != nil {
		return x.Stuno
	}
	return ""
}

func (x *CreateStudentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStudentRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type GetStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stuno         string                 `protobuf:"bytes,1,opt,name=stuno,proto3" json:"stuno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentRequest) Reset() {
	*x = GetStudentRequest{}
	mi := &file_student_student_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentRequest) ProtoMessage() {}

func (x *GetStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_student_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentRequest.ProtoReflect.Descriptor instead.
func (*GetStudentRequest) Descriptor() ([]byte, []int) {
	return file_student_student_proto_rawDescGZIP(), []int{1}
}

func (x *GetStudentRequest) GetStuno() string {
	if x != nil {
		return x.Stuno
	}
	return ""
}

type Student struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Stuno         string                 `protobuf:"bytes,2,opt,name=stuno,proto3" json:"stuno,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Fct           string                 `protobuf:"bytes,6,opt,name=fct,proto3" json:"fct,omitempty"`
	Lct           string                 `protobuf:"bytes,7,opt,name=lct,proto3" json:"lct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_student_student_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_student_student_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_student_student_proto_rawDescGZIP(), []int{2}
}

func (x *Student) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Student) GetStuno() string {
	if x != nil {
		return x.Stuno
	}
	return ""
}

func (x *Student) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Student) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Student) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Student) GetFct() string {
	if x != nil {
		return x.Fct
	}
	return ""
}

func (x *Student) GetLct() string {
	if x != nil {
		return x.Lct
	}
	return ""
}

var File_student_student_proto protoreflect.FileDescriptor

const file_student_student_proto_rawDesc = "" +
	"\n" +
	"\x15student/student.proto\x12\astudent\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/descriptor.proto\"R\n" +
	"\x14CreateStudentRequest\x12\x14\n" +
	"\x05stuno\x18\x01 \x01(\tR\x05stuno\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\")\n" +
	"\x11GetStudentRequest\x12\x14\n" +
	"\x05stuno\x18\x01 \x01(\tR\x05stuno\"\x93\x01\n" +
	"\aStudent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05stuno\x18\x02 \x01(\tR\x05stuno\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12\x10\n" +
	"\x03fct\x18\x06 \x01(\tR\x03fct\x12\x10\n" +
	"\x03lct\x18\a \x01(\tR\x03lct2\xdd\x01\n" +
	"\x0estudentService\x12^\n" +
	"\rcreateStudent\x12\x1d.student.CreateStudentRequest\x1a\x10.student.Student\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*b\x01*\"\x0estudent/create\x12k\n" +
	"\n" +
	"getStudent\x12\x1a.student.GetStudentRequest\x1a\x10.student.Student\"/\x82\xd3\xe4\x93\x02)Z\x10b\x01*\x12\vstudent/getb\x01*\x12\x12student/get/:StunoB\x1cZ\x1aag-layout-demo/api/studentb\x06proto3"

var (
	file_student_student_proto_rawDescOnce sync.Once
	file_student_student_proto_rawDescData []byte
)

func file_student_student_proto_rawDescGZIP() []byte {
	file_student_student_proto_rawDescOnce.Do(func() {
		file_student_student_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_student_student_proto_rawDesc), len(file_student_student_proto_rawDesc)))
	})
	return file_student_student_proto_rawDescData
}

var file_student_student_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_student_student_proto_goTypes = []any{
	(*CreateStudentRequest)(nil), // 0: student.CreateStudentRequest
	(*GetStudentRequest)(nil),    // 1: student.GetStudentRequest
	(*Student)(nil),              // 2: student.Student
}
var file_student_student_proto_depIdxs = []int32{
	0, // 0: student.studentService.createStudent:input_type -> student.CreateStudentRequest
	1, // 1: student.studentService.getStudent:input_type -> student.GetStudentRequest
	2, // 2: student.studentService.createStudent:output_type -> student.Student
	2, // 3: student.studentService.getStudent:output_type -> student.Student
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_student_student_proto_init() }
func file_student_student_proto_init() {
	if File_student_student_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_student_student_proto_rawDesc), len(file_student_student_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_student_student_proto_goTypes,
		DependencyIndexes: file_student_student_proto_depIdxs,
		MessageInfos:      file_student_student_proto_msgTypes,
	}.Build()
	File_student_student_proto = out.File
	file_student_student_proto_goTypes = nil
	file_student_student_proto_depIdxs = nil
}
