// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
//
// GenScope: package_group
// Versions:
//   - agserver: v0.0.1
//   - protoc: v6.33.1
// Source:
//   - hzw/hzw.proto

package hzw

import (
	"context"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
)

// HzwHello defines the server interface for the HzwHello service.
type HzwHello interface {
	HelloHzw(context.Context, *HzwRequest) (*HzwReply, error)
	HelloHzwStream(stream HzwHello_HelloHzwStreamServer) (err error)
}

// HzwHello_HelloHzwStreamServer
type HzwHello_HelloHzwStreamServer interface {
	streaming.Stream
	Recv() (*HzwRequest, error)
	Send(*HzwReply) error
}
