// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
// Code generated by agserver. DO NOT EDIT!!!
//
// GenScope: module
// Generate time: 2025-09-19 16:58:27
// Versions:
//   - agserver: v0.0.1
//   - protoc: v6.31.1
// Source:
//   - api/hzw/hellostreaming.proto
//   - api/hzw/hzw2.proto
//   - api/hzw/hzw.proto
//   - api/logs/logapi.proto

package api

import (
	adpinit "ag-layout-demo/api/adpinit"
	fx "go.uber.org/fx"
)

// FxAdapterModule return adapter fx module
func FxAdapterModule() fx.Option {
	fxAdapterOpts := adpinit.GetFxAdapterOpt()
	return fx.Module("fx-adapter", fxAdapterOpts...)
}
